#pragma once

#define READ_OFFSET 0x80

// Video Mode Registers
#define VM0_VIDEO_MODE_0                     0x00
#define VM0_VIDEO_MODE_0_READ                (VM0_VIDEO_MODE_0 | READ_OFFSET)

#define VM1_VIDEO_MODE_1                     0x01
#define VM1_VIDEO_MODE_1_READ                (VM1_VIDEO_MODE_1 | READ_OFFSET)

// Offset Registers
#define HOS_HORIZONTAL_OFFSET                0x02
#define HOS_HORIZONTAL_OFFSET_READ           (HOS_HORIZONTAL_OFFSET | READ_OFFSET)

#define VOS_VERTICAL_OFFSET                  0x03
#define VOS_VERTICAL_OFFSET_READ             (VOS_VERTICAL_OFFSET | READ_OFFSET)

// Display Memory
#define DMM_DISPLAY_MEMORY_MODE              0x04
#define DMM_DISPLAY_MEMORY_MODE_READ         (DMM_DISPLAY_MEMORY_MODE | READ_OFFSET)

#define DMAH_DISPLAY_MEMORY_ADDRESS_HIGH     0x05
#define DMAH_DISPLAY_MEMORY_ADDRESS_HIGH_READ (DMAH_DISPLAY_MEMORY_ADDRESS_HIGH | READ_OFFSET)

#define DMAL_DISPLAY_MEMORY_ADDRESS_LOW      0x06
#define DMAL_DISPLAY_MEMORY_ADDRESS_LOW_READ (DMAL_DISPLAY_MEMORY_ADDRESS_LOW | READ_OFFSET)

#define DMDI_DISPLAY_MEMORY_DATA_IN          0x07
#define DMDI_DISPLAY_MEMORY_DATA_IN_READ     (DMDI_DISPLAY_MEMORY_DATA_IN | READ_OFFSET)

// Character Memory
#define CMM_CHARACTER_MEMORY_MODE            0x08
#define CMM_CHARACTER_MEMORY_MODE_READ       (CMM_CHARACTER_MEMORY_MODE | READ_OFFSET)

#define CMAH_CHARACTER_MEMORY_ADDRESS_HIGH   0x09
#define CMAH_CHARACTER_MEMORY_ADDRESS_HIGH_READ (CMAH_CHARACTER_MEMORY_ADDRESS_HIGH | READ_OFFSET)

#define CMAL_CHARACTER_MEMORY_ADDRESS_LOW    0x0A
#define CMAL_CHARACTER_MEMORY_ADDRESS_LOW_READ (CMAL_CHARACTER_MEMORY_ADDRESS_LOW | READ_OFFSET)

#define CMDI_CHARACTER_MEMORY_DATA_IN        0x0B
#define CMDI_CHARACTER_MEMORY_DATA_IN_READ   (CMDI_CHARACTER_MEMORY_DATA_IN | READ_OFFSET)

// OSD
#define OSDM_OSD_INSERTION_MUX               0x0C
#define OSDM_OSD_INSERTION_MUX_READ          (OSDM_OSD_INSERTION_MUX | READ_OFFSET)

// Row Brightness Registers
#define RB0_ROW_0_BRIGHTNESS                 0x10
#define RB0_ROW_0_BRIGHTNESS_READ            (RB0_ROW_0_BRIGHTNESS | READ_OFFSET)

#define RB1_ROW_1_BRIGHTNESS                 0x11
#define RB1_ROW_1_BRIGHTNESS_READ            (RB1_ROW_1_BRIGHTNESS | READ_OFFSET)

#define RB2_ROW_2_BRIGHTNESS                 0x12
#define RB2_ROW_2_BRIGHTNESS_READ            (RB2_ROW_2_BRIGHTNESS | READ_OFFSET)

#define RB3_ROW_3_BRIGHTNESS                 0x13
#define RB3_ROW_3_BRIGHTNESS_READ            (RB3_ROW_3_BRIGHTNESS | READ_OFFSET)

#define RB4_ROW_4_BRIGHTNESS                 0x14
#define RB4_ROW_4_BRIGHTNESS_READ            (RB4_ROW_4_BRIGHTNESS | READ_OFFSET)

#define RB5_ROW_5_BRIGHTNESS                 0x15
#define RB5_ROW_5_BRIGHTNESS_READ            (RB5_ROW_5_BRIGHTNESS | READ_OFFSET)

#define RB6_ROW_6_BRIGHTNESS                 0x16
#define RB6_ROW_6_BRIGHTNESS_READ            (RB6_ROW_6_BRIGHTNESS | READ_OFFSET)

#define RB7_ROW_7_BRIGHTNESS                 0x17
#define RB7_ROW_7_BRIGHTNESS_READ            (RB7_ROW_7_BRIGHTNESS | READ_OFFSET)

#define RB8_ROW_8_BRIGHTNESS                 0x18
#define RB8_ROW_8_BRIGHTNESS_READ            (RB8_ROW_8_BRIGHTNESS | READ_OFFSET)

#define RB9_ROW_9_BRIGHTNESS                 0x19
#define RB9_ROW_9_BRIGHTNESS_READ            (RB9_ROW_9_BRIGHTNESS | READ_OFFSET)

#define RB10_ROW_10_BRIGHTNESS               0x1A
#define RB10_ROW_10_BRIGHTNESS_READ          (RB10_ROW_10_BRIGHTNESS | READ_OFFSET)

#define RB11_ROW_11_BRIGHTNESS               0x1B
#define RB11_ROW_11_BRIGHTNESS_READ          (RB11_ROW_11_BRIGHTNESS | READ_OFFSET)

#define RB12_ROW_12_BRIGHTNESS               0x1C
#define RB12_ROW_12_BRIGHTNESS_READ          (RB12_ROW_12_BRIGHTNESS | READ_OFFSET)

#define RB13_ROW_13_BRIGHTNESS               0x1D
#define RB13_ROW_13_BRIGHTNESS_READ          (RB13_ROW_13_BRIGHTNESS | READ_OFFSET)

#define RB14_ROW_14_BRIGHTNESS               0x1E
#define RB14_ROW_14_BRIGHTNESS_READ          (RB14_ROW_14_BRIGHTNESS | READ_OFFSET)

#define RB15_ROW_15_BRIGHTNESS               0x1F
#define RB15_ROW_15_BRIGHTNESS_READ          (RB15_ROW_15_BRIGHTNESS | READ_OFFSET)

// OSD Black Level
#define OSDBL_OSD_BLACK_LEVEL                0x6C
#define OSDBL_OSD_BLACK_LEVEL_READ           (OSDBL_OSD_BLACK_LEVEL | READ_OFFSET)

// Special Function (Variable High Nibble)
#define STAT_STATUS(base)                    ((base) | READ_OFFSET)     // AxH
#define DMDO_DISPLAY_MEMORY_DATA_OUT(base)   ((base) | READ_OFFSET)     // BxH
#define CMDO_CHARACTER_MEMORY_DATA_OUT(base) ((base) | READ_OFFSET)     // CxH