#pragma once

#define READ_OFFSET 0x80

// Video Mode Registers
#define VM0_VIDEO_MODE_0                     0x00
#define VM0_VIDEO_MODE_0_READ                (VM0_VIDEO_MODE_0 | READ_OFFSET)

#define VM1_VIDEO_MODE_1                     0x01
#define VM1_VIDEO_MODE_1_READ                (VM1_VIDEO_MODE_1 | READ_OFFSET)

// Offset Registers
#define HOS_HORIZONTAL_OFFSET                0x02
#define HOS_HORIZONTAL_OFFSET_READ           (HOS_HORIZONTAL_OFFSET | READ_OFFSET)

#define VOS_VERTICAL_OFFSET                  0x03
#define VOS_VERTICAL_OFFSET_READ             (VOS_VERTICAL_OFFSET | READ_OFFSET)

// Display Memory
#define DMM_DISPLAY_MEMORY_MODE              0x04
#define DMM_DISPLAY_MEMORY_MODE_READ         (DMM_DISPLAY_MEMORY_MODE | READ_OFFSET)

#define DMAH_DISPLAY_MEMORY_ADDRESS_HIGH     0x05
#define DMAH_DISPLAY_MEMORY_ADDRESS_HIGH_READ (DMAH_DISPLAY_MEMORY_ADDRESS_HIGH | READ_OFFSET)

#define DMAL_DISPLAY_MEMORY_ADDRESS_LOW      0x06
#define DMAL_DISPLAY_MEMORY_ADDRESS_LOW_READ (DMAL_DISPLAY_MEMORY_ADDRESS_LOW | READ_OFFSET)

#define DMDI_DISPLAY_MEMORY_DATA_IN          0x07
#define DMDI_DISPLAY_MEMORY_DATA_IN_READ     (DMDI_DISPLAY_MEMORY_DATA_IN | READ_OFFSET)

// Character Memory
#define CMM_CHARACTER_MEMORY_MODE            0x08
#define CMM_CHARACTER_MEMORY_MODE_READ       (CMM_CHARACTER_MEMORY_MODE | READ_OFFSET)

#define CMAH_CHARACTER_MEMORY_ADDRESS_HIGH   0x09
#define CMAH_CHARACTER_MEMORY_ADDRESS_HIGH_READ (CMAH_CHARACTER_MEMORY_ADDRESS_HIGH | READ_OFFSET)

#define CMAL_CHARACTER_MEMORY_ADDRESS_LOW    0x0A
#define CMAL_CHARACTER_MEMORY_ADDRESS_LOW_READ (CMAL_CHARACTER_MEMORY_ADDRESS_LOW | READ_OFFSET)

#define CMDI_CHARACTER_MEMORY_DATA_IN        0x0B
#define CMDI_CHARACTER_MEMORY_DATA_IN_READ   (CMDI_CHARACTER_MEMORY_DATA_IN | READ_OFFSET)

// OSD
#define OSDM_OSD_INSERTION_MUX               0x0C
#define OSDM_OSD_INSERTION_MUX_READ          (OSDM_OSD_INSERTION_MUX | READ_OFFSET)

// Row Brightness Registers
#define ROW_BRIGHTNESS                       0x10 // add the desired row integer to reach the correct memory address
#define ROW_BRIGHTNESS_READ                  (ROW_BRIGHTNESS | READ_OFFSET) // add the desired row integer to reach the correct memory address

// OSD Black Level
#define OSDBL_OSD_BLACK_LEVEL                0x6C
#define OSDBL_OSD_BLACK_LEVEL_READ           (OSDBL_OSD_BLACK_LEVEL | READ_OFFSET)

// Special Functions
#define STATUS                               0xA0
#define DISPLAY_MEMORY_DATA_OUT              0xB0
#define CMDO_CHARACTER_MEMORY_DATA_OUT       0xC0